### PR TITLE
Added function to convert through hole pads to via's

### PR DESCRIPTION
**Pull request by coolio986**

### CODE REVIEW

**Comment by urish** [comment]
Thanks a bunch!

Can you also add a test case for this?

Test cases live in [board.spec.ts](https://github.com/wokwi/easyeda2kicad/blob/master/src/board.spec.ts) and should be pretty straightforward - you just copy an example input from EasyEDA file, and the corresponding output from the KiCAD file (after you verified it's what you expected), and then use that as a basis for test. Please let me know if you need any assistance with this.

**Comment by coolio986** [comment]
Yep, I well add a test soon. Was more focused on getting the code to work on my end, but I will follow up. This is an important tool, I will get it done!

**Comment by urish** [comment]
Thanks!

**Comment by urish** [comment]
Also, I see that rect/polygon pads are not supported. It seems like the way to go with rect pads would be to wrap them in a footprint, similar to how we do with hole (`convertHole()`). You can find an example of an EasyEDA PCB with a RECT pad in #28.

**Comment by coolio986** [comment]
Does the source need to be committed for the test to work?

**Comment by coolio986** [comment]
RECT pads are already converted by the existing function convertPad(), no need to wrap that.
As for other polygons, I have not yet come across that. But I can attempt to simulate that in easyeda.

**Comment by urish** [comment]
Thank you! Also make sure you rebase your code to latest changes from master, I have done some changes to the tests to make them simpler. Basically, now all tests call `convertShape()`, and pass in an easyEDA shape string. e.g.: https://github.com/wokwi/easyeda2kicad/blob/ebea970323f6244fa12b8fab898e9c6f5519bb65/src/board.spec.ts#L93

**Comment by coolio986** [comment]
This is ready

**Comment by urish** [comment]
Thank you! Can you please rebase your branch on top of master? Otherwise, it is very hard to tell your changes (if you look at the [diff](https://github.com/wokwi/easyeda2kicad/pull/26/files) you can see it contains other changes as well).

To rebase, first add this repo as upstream (if you haven't done so), using:

```
git remote add upstream https://github.com/wokwi/easyeda2kicad
```

and then fetch the upstream and rebase:

```
git fetch upstream
git rebase 
```

and follow the prompts (you may have to resolve some conflicts along the way). Perhaps there is also a way to rebase via Github UI, I'm not sure (but you can google it if you like). 

Once you are happy with the result, you can force-push it to your branch by `git push -f` (just double-check that all your changes are there before you force-push)

Please let me know if you have any questions!

**Comment by coolio986** [comment]
Done

**Comment by urish** [comment]
Did you push the changes? I can't see any updates to [list of commits](https://github.com/wokwi/easyeda2kicad/pull/26/commits) in the pull request

**Comment by coolio986** [comment]
Yes I pushed as request. I followed the instructions as instructed, and all commands completed successfully.

**Comment by urish** [comment]
It seems like I might have been wrong with the commands, as I still see the unrelated commits in the PR. If you are interested, we can try to set up an online session to look at it together, or I can try to check with a friend who is a git master (wrote this [great book](https://rebase-book.com/)) to see if he could chime in here. What works best for you?

**Comment by coolio986** [comment]
I think what would work best is to re clone your repository from the latest and re apply my changes so you can see what is changed.

**Comment by urish** [comment]
Alright, do you need any help with that?

**Pull request closed without merging**
